# Generated by Django 3.2 on 2021-04-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('logno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('logname', models.CharField(max_length=10)),
                ('doc', models.CharField(max_length=3000)),
                ('remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('empno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empwd', models.CharField(max_length=10)),
                ('empname', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('pos', models.CharField(max_length=5)),
                ('group', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('storyno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('func', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('misno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('misname', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('ddl', models.DateTimeField()),
                ('group', models.CharField(max_length=10, null=True)),
                ('person', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
