# Generated by Django 3.2 on 2021-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='stakeholder',
            field=models.CharField(default='未知', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(default='已开始', max_length=20),
        ),
    ]
