# Generated by Django 3.2 on 2021-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0002_auto_20210414_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='stakeholder',
            field=models.CharField(default='未知', max_length=20),
        ),
    ]
