# Generated by Django 3.2 on 2021-04-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0003_story_stakeholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='group',
            new_name='taskgroup',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='misname',
            new_name='taskname',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='misno',
            new_name='taskno',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='person',
            new_name='taskperson',
        ),
        migrations.AlterField(
            model_name='task',
            name='ddl',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
