# Generated by Django 3.2 on 2021-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0004_auto_20210415_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='gb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbno', models.CharField(max_length=20)),
                ('gbname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select1', models.CharField(max_length=10)),
                ('select2', models.CharField(max_length=10)),
                ('select3', models.CharField(max_length=10)),
                ('select4', models.CharField(max_length=10)),
                ('select5', models.CharField(max_length=10)),
                ('select6', models.CharField(max_length=10)),
                ('select7', models.CharField(max_length=10)),
                ('select8', models.CharField(max_length=10)),
                ('select9', models.CharField(max_length=10)),
                ('select10', models.CharField(max_length=10)),
                ('select11', models.CharField(max_length=10)),
            ],
        ),
    ]
