# Generated by Django 3.2 on 2021-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0005_gb_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gb',
            name='id',
        ),
        migrations.AlterField(
            model_name='gb',
            name='gbno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
