# Generated by Django 3.2 on 2021-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0006_auto_20210415_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='hd',
            fields=[
                ('hdno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hdname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='que',
            fields=[
                ('queno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quename', models.CharField(max_length=200)),
                ('quemodel', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.AlterField(
            model_name='log',
            name='doc',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='pos',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ddl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
