# Generated by Django 3.2 on 2021-04-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0007_auto_20210425_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='func',
        ),
    ]
