# Generated by Django 3.2 on 2021-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0008_remove_story_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='hd',
            name='hdstyle',
            field=models.CharField(default='普通用户', max_length=20),
        ),
    ]
