# Generated by Django 3.2 on 2021-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0009_hd_hdstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('itviewno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('itviewmodel', models.CharField(max_length=20)),
                ('itviewque', models.CharField(max_length=200)),
                ('itviewans', models.CharField(max_length=200)),
            ],
        ),
    ]
