# Generated by Django 3.2 on 2021-04-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0010_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='role',
        ),
    ]
