# Generated by Django 3.2 on 2021-04-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0011_remove_story_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='queans',
            field=models.CharField(default='未输入答案', max_length=200),
        ),
    ]
