# Generated by Django 3.2 on 2021-04-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0012_que_queans'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='quehd',
            field=models.CharField(default='尚未知', max_length=20),
        ),
    ]
