# Generated by Django 3.2 on 2021-05-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0013_que_quehd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='que',
            name='quehd',
        ),
        migrations.AddField(
            model_name='story',
            name='field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='itview',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='quenaire',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
