# Generated by Django 3.2 on 2021-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0014_auto_20210514_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='role',
            field=models.CharField(default='未知', max_length=20),
        ),
    ]
