# Generated by Django 3.2 on 2021-05-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0015_story_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
    ]
