# Generated by Django 3.2 on 2021-05-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0016_alter_members_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='itviewmodel',
        ),
    ]
