# Generated by Django 3.2 on 2021-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0017_remove_interview_itviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='remarks',
            field=models.CharField(default='无', max_length=500, null=True),
        ),
    ]
