# Generated by Django 3.2 on 2021-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWEB', '0018_alter_story_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.CharField(max_length=1000)),
                ('goal', models.CharField(max_length=1000)),
                ('success', models.CharField(max_length=1000)),
            ],
        ),
    ]
